### ISSUE TITLE
Add PDF Download Feature for Completed Prescription in Doctor Review Component

### ISSUE THREAD

**Issue by vinaytheprogrammer** [vinaytheprogrammer/DispensaryMinor#10]
**Description:** We need to extend the functionality of the DoctorReview component by implementing a feature that allows doctors to download a PDF of the completed prescription after they submit it.

**Key Requirements:**
Capture Prescription Data:

The current DoctorReview component captures several fields, including:
Patient Details (Name, Age, Phone, Weight, Height, BP, BG, SPO2, Complaints, History).
Doctor’s input (Clinical Findings, Medicines, Reports, Doctor's Name, Doctor's Phone, Advice).
**Generate PDF:**

After submitting the form, provide a button that enables users to download the completed prescription as a PDF.
Ensure the layout is clean and readable in PDF format, with patient and doctor details, medicines prescribed, clinical findings, etc.
Utilize libraries such as jsPDF or html2pdf for this feature.
**PDF Layout:**

Structure the PDF layout professionally, mimicking a traditional prescription format.
**Include:**
Clinic or Doctor’s Name (header).
Patient Information.
Prescribed Medicines.
Doctor's Advice.
Footer with the doctor's signature and date of issuance.
**Ensure Accessibility:**

Ensure that the feature works smoothly on both desktop and mobile devices.
Ensure that the download is initiated without leaving the current page.
**Steps to Implement:**
Fetch the data submitted by the doctor in the handleSubmit method.
Pass the data to a PDF generation function once the doctor confirms the submission.
Add a "Download PDF" button to the UI, which should become available only after successful submission.
Format the content for the PDF using jsPDF or html2pdf and ensure the layout reflects typical prescription formatting.
**Additional Notes:**

It would be helpful to provide a preview of the PDF before downloading.
Ensure that the component remains responsive and that downloading the PDF doesn't affect the flow of form submissions.

**Comment by Zish303** [comment]
@vinaytheprogrammer I work on this feature. Please assign it to me.

**Comment by vinaytheprogrammer** [comment]
@Zish303 go ahead

**Comment by vinaytheprogrammer** [comment]
@Zish303 any updates?

**Comment by Zish303** [comment]
I'm working on it..

**Comment by Zish303** [comment]
I am also open to collaborate with other contributor on this feature.
