### ISSUE TITLE
Add "Dashboard" Button to Navigate to Appointment Page

### ISSUE THREAD

**Issue by vinaytheprogrammer** [vinaytheprogrammer/DispensaryMinor#2]
**Description:**
We need to add a "Dashboard" button on the main page that redirects the user to the /appointment page when clicked. This will improve navigation for users who want quick access to their appointment management.

**Expected Behavior:**
A new "Dashboard" button should be added to the UI.
When clicked, the button should navigate the user to the /appointment page.

**Proposed Solution:**
Add the button to the appropriate location in the UI (suggestion: top-right corner or as part of the navigation bar).
Ensure the button is clearly labeled as "Dashboard."
Link it to the /appointment route.

**Additional Context:**
This feature will provide an easier and quicker way for users to access the appointment page without manually navigating through other sections.

![image](https://github.com/user-attachments/assets/8470ac48-664f-42b7-bef1-9b4d9130410e)

**Comment by tharikashree** [comment]
Hey can i work on this

**Comment by vinaytheprogrammer** [comment]
@tharikashree this issue has been resolved I'm going to create several issues. please look into those.
