### ISSUE TITLE
Improve Responsiveness for Mobile and Tablet Views

### ISSUE THREAD

**Issue by vinaytheprogrammer** [vinaytheprogrammer/DispensaryMinor#5]
**Description:**

The current design of the application is not fully optimized for mobile and tablet views. Elements like forms, navigation bars, and content sections are not adjusting properly to different screen sizes, causing issues with user experience.

**Task:**

Implement responsive design techniques for the following views:

Mobile view (for devices with screen width below 768px)
Tablet view (for devices with screen width between 768px and 1024px)
Ensure that the following sections of the application are responsive:

Login/Signup pages
Appointment creation form
Doctor-patient communication section
Navigation bar and header
Patient details section
Use media queries and/or frameworks like Tailwind CSS, Bootstrap, or any custom CSS rules to adapt the layout.

Test across different devices and browsers to ensure consistent behavior.

**Acceptance Criteria:**

Application layout should adjust seamlessly for mobile and tablet views.
No content should overflow or be cut off on smaller screens.
Navigation and forms should be easily accessible and usable on mobile and tablet devices.
Application should remain visually consistent with the desktop version.
Additional Information: If applicable, include screenshots of how the current design looks on mobile and tablet views and specify the areas causing issues.

![WhatsApp Image 2024-10-06 at 21 32 15_28ba6a27](https://github.com/user-attachments/assets/53bd2e4e-d7be-4b34-92e1-6ec0d76fe8ca)

**Comment by Sharjeel21** [comment]
I can do this will you assign this to me.

**Comment by vinaytheprogrammer** [comment]
@786Aaqueeb i already told him to do this, but i will prefer FCFS so go ahead

**Comment by vinaytheprogrammer** [comment]
@Sharjeel21 but read Acceptance Criteria carefully
