### ISSUE TITLE
Session Ends on Page Refresh

### ISSUE THREAD

**Issue by vinaytheprogrammer** [vinaytheprogrammer/DispensaryMinor#6]
**Description:**
When refreshing the page, the user is automatically logged out. The session is not being preserved, causing an unwanted logout.

**Steps to Reproduce:**
Login to the application.
Navigate to any page.
Refresh the page.
Observe that the user is logged out.

**Expected Behavior:**
The session should persist even after refreshing the page, keeping the user logged in.

**Actual Behavior:**
The user is logged out upon page refresh, requiring re-login.

**Possible Causes:**
Session storage not being handled correctly: The user’s session token might not be stored in a persistent storage like localStorage or sessionStorage.
Invalidation of token: The authentication token might be invalidated on refresh.
Session management issues in the backend: The session data may not be maintained properly between page reloads.

**Proposed Solution:**
Ensure the session token is stored in persistent storage (e.g., localStorage, sessionStorage).
Review the session management logic on both frontend and backend to ensure the session remains valid after a refresh.

**Environment:**
Frontend: React, React-Router-Dom
Backend: Express.js, bcryptjs, jsonwebtoken
Other libraries: axios, react-toastify, etc.

**Additional Context:**
Any additional relevant information that could assist in diagnosing the problem.

**Comment by ShravastiSiddharth** [comment]
@vinaytheprogrammer  I would like to solve this issue for you, can I work on this

**Comment by vinaytheprogrammer** [comment]
@ShravastiSiddharth ofcourse ho ahead

**Comment by vinaytheprogrammer** [comment]
@Sharjeel21 you made an amazing contribution
